spring.application.name=project-webservice-section22

# DATASOURCE
spring.datasource.url=jdbc:postgresql://localhost:5432/springboot_course

#Configured in "Edit Configurations..." Project drop down, then set in environment section
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=$SPRING_DATASOURCE_PASSWORD}

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true

jwt.secret=MYJWTSECRET
jwt.expiration=3600000